# Site setings

name: "Meryem M'hamdi"
description: 'Horace is a simple Jekyll theme for writers and bloggers. Explore it yourself.'
name: "<i class='fas fa-home'></i>"
description: 'This website is to introduce myself, my background and my current work'
meta_description: 'Jekyll template, minimal style, perfect for bloggers.'
favicon: 'favicon.ico'
baseurl: 
production_url: https://horace.netlify.com/
disqus: 'justgoodthemes'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 


# Author
author:
  name: "Meryem M'hamdi"
  image: 'authorimage2.png'
  greetings: 'Hi!'
  description: "<p> My name is Meryem M'hamdi. I am a PhD candidate in Computer Science and a research assistant at
    <a href=https://www.isi.edu/> Information Sciences Institute (ISI) </a> in <a href=https://www.usc.edu/>
    University of Southern California (USC) </a> in Los Angeles. <br> <br>
    I work in Natural Language Processing Group under the supervision of <a href=https://www.isi.edu/~jonmay/> Prof. Jonathan May </a>.
    My main research interest is to adapt cross-lingual unsupervised approaches to different downstream applications including event extraction,
    dependency parsing and studying their probing capabilities at large. My aim is to devise novel approaches for learning and tuning universal
    multilingual representations to different domains of applications and studying their generalization especially in resource setting,
    zero/few shot learning scenarios while being evaluated with different flavours of transfer learning. </p>"
  bio: 'Prior to joining ISI, Meryem holds a Master in Computer Science from <a href=https://www.epfl.ch/> Ecole Polytechnique Federale de Lausanne (EPFL) </a>
  in Swizerland and is currently pursuing her PhD in Computer Science with special focus on Natural Language Processing in
  <a href=https://www.usc.edu/> University of Southern California (USC) </a> in Los Angeles. Her research aspirations come
  from her passion for learning new languages and discovering new cultures through traveling. '

# Contact form setings
email: meryemmhamdi1@gmail.com
#contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
contact_page_description: ""
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
#twitter: 'username'

github: 'meryemmhamdi1'
#codepen: 'username'
#dribbble: 'username'
#medium: '@username'
linkedin: 'meryem-m-hamdi-69964980'
facebook: 'Meryem.Mhamdi.2'
instagram: 'meryem.mhamdi'
google-scholar:
#pinterest: 'username'

#producthunt: '@username'

# Navigation
navigation:
  - text: "About  <i class='fas fa-user'></i>"
    url: /about/
  - text: "Projects   <i class='fas fa-briefcase'></i>"
    url: /projects-publications/
  - text: "Contact   <i class='fas fa-comments'></i>"
    url: /contact/


# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
