# Site setings
name: 'Meryem M'hamdi'
description: 'This website is to introduce myself, my background and my current work'
meta_description: 'Jekyll template, minimal style, perfect for bloggers.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://horace.netlify.com/
disqus: 'justgoodthemes'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 


# Author
author:
  name: 'Meryem M'hamdi'
  image: 'authorimage.jpg'
  greetings: 'Hi there!'
  description: "My name is Meryem M'hamdi. I am a candidate PhD student in computer science and a research assistant at [Information Sciences Institute (ISI)](https://www.isi.edu/) in [University of Southern California (USC)](https://www.usc.edu/), Los Angeles. I work in Natural Language Processing Group under the supervision of Prof. Jonathan May. My research purpose is to adapt a cross-domain and multilingual approach to different semantic tasks mainly related to dialogue systems and information extraction in low resource setting. It's nice to meet you :)"
  bio: 'Meryem obtained a Bachelor of Science in Computer Science from [Al Akhawayn University (AUI)](http://www.aui.ma/en/) in Morocco and a Master in Computer Science from [Ecole Polytechnique Federale de Lausanne (EPFL)](https://www.epfl.ch/) in Swizerland. My research aspirations come from her passion for learning new languages and discovering new cultures through traveling.'

# Contact form setings
email: meryemmhamdi1@gmail.com
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'username'
facebook: 'username'
github: 'meryemmhamdi1'
codepen: 'username'
dribbble: 'username'
medium: '@username'
instagram: 'username'
pinterest: 'username'
linkedin: 'meryem-m-hamdi-69964980'
producthunt: '@username'

# Navigation
navigation:
  - text: About
    url: /about/
  - text: Style Guide
    url: /style-guide/
  - text: Contact Me
    url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
