# Site setings

name: "Meryem M'hamdi"
description: 'Horace is a simple Jekyll theme for writers and bloggers. Explore it yourself.'
name: "<i class='fas fa-home'></i>"
description: 'This website is to introduce myself, my background and my current work'
meta_description: 'Jekyll template, minimal style, perfect for bloggers.'
favicon: 'favicon.ico'
baseurl: 
production_url: https://horace.netlify.com/
disqus: 'justgoodthemes'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 


# Author
author:
  name: "Meryem M'hamdi"
  image: 'authorimage2.png'
  greetings: 'Hi!'
  description: "<p> My name is Meryem M'hamdi. 
  I recently earned my PhD in Computer Science from the University of Southern California. 
  My research focused on advancing multilingual language models beyond traditional data-intensive, identically-distributed approaches. 
  Specifically, I developed human-like cross-lingual transfer learning techniques using meta-learning, continual learning, and curriculum learning. 
  These innovations enhance model generalization across low-resource and unseen languages, applied effectively in multilingual information extraction, natural language understanding, and semantic search applications. 
  <br> <br>  During my journey, I collaborated with many leading multinational companies including Sony, Swisscom, Adobe Research, and more recently Microsoft. 
  <br> <br>  With a rich background in computer science and representation learning and a focus on applied research, my journey has led me to Microsoft, where I currently serve as both a Data Scientist II. At the forefront of Bing's multimedia team, my efforts have been instrumental in advancing user embeddings towards more personalized recommendation systems, building from scratch a state-of-the-art large language model to refine the user experience. 
  <br> <br>  As a Moroccan, I am fluent in four languages/dialects: Standard Arabic, Moroccan Arabic, French, and English, with basic proficiency in Spanish and German. I have a passion for learning new languages, which broadens my cultural understanding. I also enjoy traveling; I've visited over 10 countries and have lived in three continents, including Africa (my place of origin) and Europe, where I pursued my Master's degree. In my leisure time, I indulge in activities like yoga, zumba, and occasional singing. </p>"
  bio: 'Prior to joining ISI, Meryem holds a Master in Computer Science from <a href=https://www.epfl.ch/> Ecole Polytechnique Federale de Lausanne (EPFL) </a>
  in Swizerland and is currently pursuing her PhD in Computer Science with special focus on Natural Language Processing in
  <a href=https://www.usc.edu/> University of Southern California (USC) </a> in Los Angeles. Her research aspirations come
  from her passion for learning new languages and discovering new cultures through traveling. '

# Contact form setings
email: meryemmhamdi1@gmail.com
#contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
contact_page_description: ""
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'MeryemMhamdi1'
github: 'meryemmhamdi1'
#codepen: 'username'
#dribbble: 'username'
#medium: '@username'
linkedin: 'meryem-m-hamdi-69964980'
# facebook: 'Meryem.Mhamdi.2'
# instagram: 'meryem.mhamdi'
google-scholar: 'https://scholar.google.com/citations?user=7xflIKgAAAAJ&hl=en'
#pinterest: 'username'

#producthunt: '@username'

# Navigation
navigation:
  - text: "About  <i class='fas fa-user'></i>"
    url: /about/
  - text: "Projects   <i class='fas fa-briefcase'></i>"
    url: /projects-publications/
  - text: "Contact   <i class='fas fa-comments'></i>"
    url: /contact/


# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
